[package]
name = "orbis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Your Linux software, in one place."
default-run = "orbis"

[[bin]]
name = "orbis"
path = "src/main.rs"

[dependencies]
clap.workspace = true
orbis-core = { path = "../orbis-core" }
serde.workspace = true
serde_json.workspace = true
ratatui.workspace = true
crossterm.workspace = true
