[package]
name = "orbis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Your Linux software, in one place."
readme = "../../README.md"
default-run = "orbis"

[[bin]]
name = "orbis"
path = "src/main.rs"

[dependencies]
clap.workspace = true
semver.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
ureq.workspace = true
xz2.workspace = true
orbis-core.workspace = true
serde.workspace = true
serde_json.workspace = true
ratatui.workspace = true
crossterm.workspace = true
unicode-width.workspace = true
